export const OWNER_LEAD_STATUSES = [
  'PENDING',
  'TIME_UPDATE_REQUESTED',
  'CUSTOMER_TIME_REQUESTED',
  'RESCHEDULE_REQUESTED',
] as const;

export const OWNER_INACTIVE_BOOKING_STATUSES = ['CANCELLED', 'REJECTED'] as const;
